line.bot:
  channel-token: '6TbWdBg80TVYSyV4sF1KFIjRfVccCW7H4eVtyxPQXrhdJSnryOnlvHF+LWS8tn1DYmLMhVVDY3YJYFytVKCVAanqywLGTaZqATIxAyTVPY9ul6XXlosufyeTwD9y3RxL+tf9Fz6EOzj9vsP5YQYFPQdB04t89/1O/w1cDnyilFU='
  channel-secret: '5ba8b1ace6e3e50a2a85b69b245cbb9f'
  handler.path: /callback